### ISSUE TITLE
ZCU216 change MAC on each boot.

### ISSUE THREAD

**Issue by chaozhou74** [PITT-HATLAB/Hatlab_RFSOC#2]
The ZCU216 with the current PYNQ 2.7 image from the QICK repo sees to have the problem of changing MAC(ether) address on each boot. This makes the DHCP IP reservation stop working, as a result, the IP address of the board will change on each reboot, which makes connecting to the board frustrating.

**Comment by hatlabcz** [comment]
This seems to be a known issue for some of the recent PYNQ images for some other boards as well (https://discuss.pynq.io/t/ethernet-mac-address-changes-everytime-restart-the-zcu104-board/2575/6).\
I tried [this solution](https://discuss.pynq.io/t/ethernet-mac-address-changes-everytime-restart-the-zcu104-board/2575/9). However, the `saveenv` command seems to be also disabled on this PYNQ image, so it doesn't work for us...

Since our goal is just to give the board a fixed MAC, I then just solved that by giving the board a static MAC.
- `sudo nano /etc/network/interfaces.d/eth0`
- add `hwaddress ether [new_mac_address]` after 
    > auto eth0
    > iface eth0 inet dhcp
   
    Note that the actual MAC address of the board should be on a sticker on the back of the main board, so it's probably good to use that as the [new_mac_address], instead of a random one like 00:11:22:33:44:55


Note that this has to be done again if a new SD card image is used.

**Comment by chaozhou74** [comment]
This seems to be a known issue for some of the recent PYNQ images for some other boards as well (https://discuss.pynq.io/t/ethernet-mac-address-changes-everytime-restart-the-zcu104-board/2575/6).\
I tried [this solution](https://discuss.pynq.io/t/ethernet-mac-address-changes-everytime-restart-the-zcu104-board/2575/9). However, the `saveenv` command seems to be also disabled on this PYNQ image, so it doesn't work for us...

Since our goal is just to give the board a fixed MAC, I then just solved that by giving the board a static MAC.
- `sudo nano /etc/network/interfaces.d/eth0`
- add `hwaddress ether [new_mac_address]` after 
    > auto eth0
    > iface eth0 inet dhcp
   
    Note that the actual MAC address of the board should be on a sticker on the back of the main board, so it's probably good to use that as the [new_mac_address], instead of a random one like 00:11:22:33:44:55


Note that this has to be done again if a new SD card image is used.
